require("Utility.ColorEnum")

BLOCK_TYPE = {
	START = COLOR.LIME, -- Lime
	STATIC_BLOCK = COLOR.WHITE, -- White
	VERTICAL_BLOCK = COLOR.LIGHT_BLUE, -- Light Blue
	HORIZONTAL_BLOCK = COLOR.DARK_BLUE, -- Dark Blue
	BOUNCE_BLOCK = COLOR.ORANGE, -- Orange
	VERTICAL_BOUNCE = COLOR.RED, -- Red
	HORIZONTAL_BOUNCE = COLOR.MAROON, -- Maroon
	ROTATING_BLOCK = COLOR.PURPLE, -- Purple
	ROTATING_BOUNCE = COLOR.PINK, -- Pink
	END = COLOR.GRAY, -- Gray
}
